## Production

### Get days this year
GET  https://smartcloudscript.de/api/date/days-this-year

### Get root
GET https://smartcloudscript.de/ HTTP/1.1

### Get Airport by icao code from smartcloud...
GET https://smartcloudscript.de/api/airport?icao=LGAV


## Development

### Get in dev
GET http://localhost:5000/api/date/days-this-year

### Get World Airports
GET http://localhost:5000/api/airport?icao=EDDK HTTP/1.1

### Set index on Airports Collection
GET http://localhost:5000/api/admin/db/createindex?key=icao

### Drop index on Airports Collection
GET http://localhost:5000/api/admin/db/dropindex?index=icao HTTP/1.1

