
### Get days this year
GET  https://smartcloudscript.de/api/date/days-this-year

### Get root
GET https://smartcloudscript.de/ HTTP/1.1

### Get in dev
GET http://localhost:5000/api/date/days-this-year

### Get Airports
GET http://localhost:5000/api/airports HTTP/1.1

### Get Airport by id
GET http://localhost:5000/api/airport/1
