version: '3.4'
x-defaults:
  service: &logging-svc
    logging: {options: {max-size: "10m", max-file: "3"}}
#create docker volumes for mongodb
volumes: 
  mongodata:
    name: "MongoData-WebDB"
  mongoconfig:
    name: "MongoConfig-WebDB"
networks: 
  Prod_Net:
    driver: bridge 
    ipam:
      driver: default 
      config: 
      - subnet: 172.28.0.0/16 

services:
  backend_db:
    <<: *logging-svc
    image: mongo
    restart: always
    container_name: backend_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - 27017:27017
    networks: 
      Prod_Net:
        ipv4_address: 172.28.0.4
    volumes: 
       - mongodata:/data/db
       - mongoconfig:/data/configdb
  frontend_api:
    <<: *logging-svc
    image: markusadocker/scs-nodejs-frontend-api:latest
    container_name: frontend_api
    ports: 
      - 5000:5000
    networks: 
      Prod_Net:
        ipv4_address: 172.28.0.5
    depends_on:
      - backend_db
  backend_api:
    <<: *logging-svc
    image: backend_api
    container_name: backend_api
    build: 
      context: ./backend/backend_api
      dockerfile: Dockerfile
    environment:
      - VaultSettings:HealthCheckTimer=25
      - VaultSettings:Backend_DB_Policy=backenddb
    volumes: 
      - ./backend/backend_api/Data/Static:/data/staticfiles
    networks: 
      Prod_Net:
        ipv4_address: 172.28.0.3
    depends_on: 
      - vault
  vault:
    <<: *logging-svc
    image: vault
    container_name: vault
    restart: always
    environment: 
      - VAULT_ADDR=http://127.0.0.1:8200
    volumes:
      - ./backend/vault/logs:/vault/logs
      - ./backend/vault/file:/vault/file
      - ./backend/vault/config:/vault/config
    ports:
      - 8200:8200
    networks: 
      Prod_Net:
        ipv4_address: 172.28.0.2
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/config.json
    