version: '3.4'
x-defaults:
  service: &logging-svc
    logging: {options: {max-size: "10m", max-file: "3"}}
#create docker volumes for mongodb
volumes: 
  mongodata:
    name: "MongoData-WebDB"
  mongoconfig:
    name: "MongoConfig-WebDB"

networks: 
  Dev_Net:
    driver: bridge 
    ipam:
      driver: default 
      config: 
      - subnet: 172.30.0.0/16 
        
        

services:
  backend_db:
    <<: *logging-svc
    image: mongo
    restart: always
    container_name: backend_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - 27018:27017
    volumes: 
       - mongodata:/data/db
       - mongoconfig:/data/configdb
    networks: 
        Dev_Net:
          ipv4_address: 172.30.0.2
  frontend_api:
    <<: *logging-svc
    image: frontend_api
    restart: always
    container_name: frontend_api
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    networks: 
        Dev_Net:
          ipv4_address: 172.30.0.3
    depends_on:
      - backend_db
  backend_api:
    <<: *logging-svc
    image: backend_api
    restart: always
    container_name: backend_api
    environment: 
      - VaultTokens.DevToken=${VaultRoot}
      - VaultSettings:HealthCheckTimer=25
      - VaultSettings:Backend_DB_Policy=backenddb
    build: 
      context: ./backend/backend_api
      dockerfile: Dockerfile
    volumes: 
      - ./backend/backend_api/Data/Static:/data/staticfiles
    networks: 
        Dev_Net:
          ipv4_address: 172.30.0.4
    depends_on: 
      - vault
  backend_graph:
    <<: *logging-svc
    image: backend_graph
    restart: always
    container_name: backend_graph
    build:
      context: ./backend/backend_graph
      dockerfile: Dockerfile
    ports:
      - 5001:80
    networks:
        Dev_Net:
          ipv4_address: 172.30.0.6
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    environment: 
      - VAULT_ADDR=http://127.0.0.1:8200
    volumes:
      - ./backend/vault/logs:/vault/logs
      - ./backend/vault/file:/vault/file
      - ./backend/vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    networks: 
        Dev_Net:
          ipv4_address: 172.30.0.5
    entrypoint:  vault server -config=/vault/config/config.json 
    
    
    
     
      
    
    
    
     
    
    
    
    
    