version: '3.4'
#create docker volumes for mongodb
volumes: 
  mongodata:
    name: "MongoData-WebDB"
  mongoconfig:
    name: "MongoConfig-WebDB"

services:
  backend_db:
    image: mongo
    restart: always
    container_name: backend_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - 27017:27017
    volumes: 
       - mongodata:/data/db
       - mongoconfig:/data/configdb
  frontend_api:
    image: frontend_api
    container_name: frontend_api
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
     
    depends_on:
      - backend_db