version: '3.4'
x-defaults:
  service: &logging-svc
    logging: {options: {max-size: "10m", max-file: "3"}}
#create docker volumes for mongodb
volumes: 
  mongodata:
    name: "MongoData-WebDB"
  mongoconfig:
    name: "MongoConfig-WebDB"

services:
  backend_db:
    <<: *logging-svc
    image: mongo
    restart: always
    container_name: backend_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - 27018:27017
    volumes: 
       - mongodata:/data/db
       - mongoconfig:/data/configdb
  frontend_api:
    <<: *logging-svc
    image: frontend_api
    container_name: frontend_api
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    depends_on:
      - backend_db
  backend_api:
    <<: *logging-svc
    image: backend_api
    container_name: backend_api
    build: 
      context: ./backend/backend_api
      dockerfile: Dockerfile
    volumes: 
      - ./backend/backend_api/Data/Static:/data/staticfiles
    depends_on: 
      - vault
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    environment: 
      - VAULT_ADDR=http://127.0.0.1:8200
      
    volumes:
      - ./backend/vault/logs:/vault/logs
      - ./backend/vault/file:/vault/file
      - ./backend/vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint:  vault server -config=/vault/config/config.json 
    
    
    
     
      
    
    
    
     
    
    
    
    
    