
### Get days this year
GET  https://smartcloudscript.de/api/date/days-this-year

### Get root
GET https://smartcloudscript.de/ HTTP/1.1

### Get in dev
GET http://localhost:5000/api/date/days-this-year