name: frontend_api Docker Image CI

on:
  push:
    branches: [ master ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD

=======
>>>>>>> d9280e005891e26becf08f06865868430233dde0
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: markusadocker/scs-nodejs-frontend-api
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        workdir: ./frontend/
        dockerfile: Dockerfile
        tags: "latest,v1"
      
  
