name: frontend_api Docker Image CI

on:
  push:
    branches: [ master ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: ./frontend/
      run: docker build . --file Dockerfile --tag scs_frontend_api:$(date +%s)
    
    - name: Push to Docker Hub
      uses: zenato/docker-action@v1.0.0
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: scs-nodejs-frontend-api
      
  
