name: frontend_api Docker Image CI

on:
  push:
    branches: [ master ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: markusadocker/scs-nodejs-frontend-api
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        workdir: ./frontend/
        dockerfile: DOCKERFILE
        tags: "latest"
      
  
