name: frontend_api Docker Image CI

on:
  push:
    branches: [ master ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Pipeflow/Dokcerflow@0.0.1
    - name: Build 2
      with:
        action: docker build . --file Dockerfile --tag frontend_api:$(date +%s)
        workdir: ./frontend/  
  
