name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Change working directory
    - working-directory: frontend
    - name: Create Docker image
      run: 
        docker build . --file Dockerfile -t frontend_api
