name: Docker Image CI

on:
  push:
    branches: [ master ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: message_api_smartcloudscirpt/frontend
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag frontend_api:$(date +%s)
